import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider, signOut } from "next-auth/react";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Header from "./header";
import ClientSessionProvider from "./client-session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSessionProvider>
          <Header />
          {children}
        </ClientSessionProvider>
      </body>
    </html>
  );
}
