import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSessionProvider from "./client-session-provider";
import { Toaster } from "@/components/ui/sonner";
// import ReactQueryProvider from "@/lib/react-query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          width: "100vw",
          height: "100vh",
          overflow: "hidden",
        }}
        className={inter.className}
      >
        {/* <ReactQueryProvider> */}
        <ClientSessionProvider>
          <Toaster
            position="top-center"
            richColors
            theme="light"
            duration={2500}
          />
          {children}
        </ClientSessionProvider>
        {/* </ReactQueryProvider> */}
      </body>
    </html>
  );
}
