import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSessionProvider from "./client-session-provider";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { DialogProvider } from "@/components/dialog-provider";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
// import ReactQueryProvider from "@/lib/react-query-provider";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ClassMaster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "font-sans antialiased grainy overflow-hidden"
          // inter.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {/* <ReactQueryProvider> */}
          <ClientSessionProvider>
            <Toaster
              position="top-center"
              richColors
              theme="light"
              duration={3500}
            />
            <Navbar />
            {children}
            <DialogProvider />
          </ClientSessionProvider>
          {/* </ReactQueryProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
